### ISSUE TITLE
AWS IAM Classes no longer available in binary

### ISSUE THREAD

**Issue by chrisoberle** [streamthoughts/jikkou#268]
**Describe the bug**
Starting in v0.25.0, software.amazon.msk.auth.iam.IAMClientCallbackHandler is no longer available in the binary.  This class is contained within the following dependency:
```
	    <dependency>
                <groupId>software.amazon.msk</groupId>
                <artifactId>aws-msk-iam-auth</artifactId>
                <version>1.1.9</version>
            </dependency>
```

**To Reproduce**
Use a configuration like this that specifies the AWS classes and sasl mechanism:
```
{
  "currentContext" : "sandbox",
  "sandbox" : {
    "configFile" : null,
    "configProps" : {
      "kafka.client.security.protocol" : "SASL_SSL",
      "kafka.client.sasl.mechanism" : "AWS_MSK_IAM",
      "kafka.client.sasl.jaas.config" : "software.amazon.msk.auth.iam.IAMLoginModule required awsProfileName=AWSPROFILE;",
      "kafka.client.sasl.client.callback.handler.class" : "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
      "kafka.client.bootstrap.servers" : "BOOTSTRAPSERVERS"
    }
  }
}
```

**Expected behavior**
Jikkou should run normally without errors.

**Screenshots/Configs**
Stacktrace
```
Error: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
org.apache.kafka.common.config.ConfigException: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:145)
        at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:245)
        at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
        at io.streamthoughts.jikkou.kafka.internals.KafkaUtils.newAdminClient(KafkaUtils.java:37)
        at io.streamthoughts.jikkou.kafka.AdminClientContext.lambda$new$0(AdminClientContext.java:110)
        at io.streamthoughts.jikkou.kafka.AdminClientContext.client(AdminClientContext.java:215)
        at io.streamthoughts.jikkou.kafka.AdminClientContext.invoke(AdminClientContext.java:155)
        at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicCollector.listAll(AdminClientKafkaTopicCollector.java:130)
        at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicController.computeReconciliationChanges(AdminClientKafkaTopicController.java:148)
        at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicController.computeReconciliationChanges(AdminClientKafkaTopicController.java:55)
        at io.streamthoughts.jikkou.api.control.BaseResourceController.reconcile(BaseResourceController.java:58)
        at io.streamthoughts.jikkou.api.DefaultApi.lambda$apply$0(DefaultApi.java:189)
        at java.base@17.0.8/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.8/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base@17.0.8/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at io.streamthoughts.jikkou.api.DefaultApi.apply(DefaultApi.java:192)
        at io.streamthoughts.jikkou.client.command.BaseResourceCommand.call(BaseResourceCommand.java:65)
        at io.streamthoughts.jikkou.client.command.BaseResourceCommand.call(BaseResourceCommand.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.streamthoughts.jikkou.client.Jikkou$1.execute(Jikkou.java:152)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.streamthoughts.jikkou.client.Jikkou.execute(Jikkou.java:135)
        at io.streamthoughts.jikkou.client.Jikkou.main(Jikkou.java:118)
```
**Runtime environment**
 - OS: MacOS (M1) Ventura 13.5.1 (22G90)
 - Jikkou: 0.25.0
 - Docker version: 20.10.24, build 297e128
 - Kafka Cluster Version: 2.8.1

**Additional context**
This works fine in 0.24.0.

**Comment by chrisoberle** [comment]
If the native image has issues for whatever reason, I wonder if it would be possible to continue to include the fatjar runner as a release artifact?

Noted also that pointing to the fatjar following a fresh local build yields the same result...so it doesn't appear to be specific to the native build:

```
/Users/coberle/code/jikkou/jikkou-cli/target/jikkou-cli-0.28.0-SNAPSHOT-runner apply -f ./topics.yaml --dry-run
org.apache.kafka.common.config.ConfigException: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
```

We are stuck on 0.24.0 until this is resolved.    thank you!

**Comment by fhussonnois** [comment]
Hi @chrisoberle, thank you for reporting this issue. I've completely forgotten to take into account `aws-msk-iam-auth` while building jikkou native image? In addition,  the `aws-msk-iam-auth`  lib doesn't seem to provide any built-in support for graalvm.

I've committed a fix which resolves the following exception:
`Error: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.`

Could you confirm that the binary version now works normally (I don't have an MSK cluster available to test it) ? You can try the `early-access` release for this : https://github.com/streamthoughts/jikkou/releases/tag/0.28.0-early-access

**Comment by chrisoberle** [comment]
Thanks so much Florian.  It looks like I'm able to get past the initial classloader issue.    There's still some issue with the native binary, though its not clear to me what could be happening.   

```
❯ export JIKKOUCONFIG=/Users/coberle/code/kafka/jikkou/config
❯ /Users/coberle/Downloads/jikkou-0.28.0-SNAPSHOT-osx-x86_64/bin/jikkou apply -f jikkou/sandbox/topics.yaml --dry-run
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:488)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at io.streamthoughts.jikkou.kafka.internals.KafkaUtils.newAdminClient(KafkaUtils.java:37)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.lambda$new$0(AdminClientContext.java:110)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.client(AdminClientContext.java:215)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.invoke(AdminClientContext.java:155)
	at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicCollector.listAll(AdminClientKafkaTopicCollector.java:130)
	at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicController.computeReconciliationChanges(AdminClientKafkaTopicController.java:148)
	at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaTopicController.computeReconciliationChanges(AdminClientKafkaTopicController.java:55)
	at io.streamthoughts.jikkou.api.control.BaseResourceController.reconcile(BaseResourceController.java:58)
	at io.streamthoughts.jikkou.api.DefaultApi.lambda$apply$0(DefaultApi.java:189)
	at java.base@17.0.8/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.8/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base@17.0.8/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base@17.0.8/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.streamthoughts.jikkou.api.DefaultApi.apply(DefaultApi.java:192)
	at io.streamthoughts.jikkou.client.command.BaseResourceCommand.call(BaseResourceCommand.java:65)
	at io.streamthoughts.jikkou.client.command.BaseResourceCommand.call(BaseResourceCommand.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at io.streamthoughts.jikkou.client.Jikkou$1.execute(Jikkou.java:153)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.streamthoughts.jikkou.client.Jikkou.execute(Jikkou.java:136)
	at io.streamthoughts.jikkou.client.Jikkou.main(Jikkou.java:119)
Caused by: org.apache.kafka.common.KafkaException: java.lang.ExceptionInInitializerError
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:522)
	... 35 more
Caused by: java.lang.ExceptionInInitializerError
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:142)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.<clinit>(EC2ResourceFetcher.java:44)
	at java.base@17.0.8/java.lang.Class.ensureInitialized(DynamicHub.java:528)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.<init>(InstanceMetadataServiceCredentialsFetcher.java:37)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:111)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:91)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:75)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.<clinit>(InstanceProfileCredentialsProvider.java:58)
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.initializeProvider(EC2ContainerCredentialsProviderWrapper.java:64)
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.<init>(EC2ContainerCredentialsProviderWrapper.java:53)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.getDefaultProvider(MSKCredentialProvider.java:134)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:113)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:103)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:99)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.lambda$configure$1(IAMClientCallbackHandler.java:54)
	at java.base@17.0.8/java.util.Optional.map(Optional.java:260)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.configure(IAMClientCallbackHandler.java:54)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:151)
	... 39 more
Caused by: java.lang.IllegalArgumentException
	at com.amazonaws.internal.config.InternalConfig.loadfrom(InternalConfig.java:260)
	at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:274)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:347)
	... 59 more
```

I'm happy to pull, locally build and see if the fatjar works if you think that would help (I see the fatjar asset has been removed from the release assets).

**Comment by chrisoberle** [comment]
Rats....no luck :(.  

```
❯ /Users/coberle/Downloads/jikkou-0.28.0-SNAPSHOT-osx-x86_64/bin/jikkou apply -f jikkou/sandbox/topics.yaml --dry-run
16:08:46.909 [main] WARN  o.a.kafka.common.utils.AppInfoParser - Error while loading kafka-version.properties: inStream parameter is null
16:08:47.095 [main] ERROR i.s.j.k.internals.KafkaBrokersReady - Error while listing Kafka nodes: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: listNodes
16:08:47.100 [kafka-admin-client-thread | adminclient-1] ERROR o.a.kafka.common.utils.KafkaThread - Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1':
java.lang.ExceptionInInitializerError: null
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:144)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:96)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:534)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/javax.security.auth.Subject.doAs(Subject.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:534)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:332)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:273)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: com.amazonaws.SdkClientException: Unable to load partition metadata from com/amazonaws/partitions/endpoints.json
	at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:82)
	at software.amazon.msk.auth.iam.internals.AuthenticationRequestParams.<clinit>(AuthenticationRequestParams.java:41)
	... 19 common frames omitted
```

Would it be possible to request that a fatjar be added back to the release assets or do we need to create our own source build?   Thanks!

**Comment by fhussonnois** [comment]
Let's go for another turn. I've added the missing resource to the native-image. 

The fatjar can be downloaded from Maven Central: [jikkou-cli-0.27.0-runner.jar](https://repo.maven.apache.org/maven2/io/streamthoughts/jikkou-cli/0.27.0/jikkou-cli-0.27.0-runner.jar). But I think it's possible to add it to the GitHub Releases for convenience.

**Comment by chrisoberle** [comment]
Thank you Florian.   No luck on the native binary, however it does look like the fat jar in maven central works.   We can update things on our end to start consuming that until some better path presents itself.

```
/Users/coberle/Downloads/jikkou-0.28.0-SNAPSHOT-osx-x86_64/bin/jikkou apply -f jikkou/sandbox/topics.yaml --dry-run
19:07:55.208 [main] ERROR i.s.j.k.internals.KafkaBrokersReady - Error while listing Kafka nodes: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: listNodes
19:07:55.212 [kafka-admin-client-thread | adminclient-1] ERROR o.a.kafka.common.utils.KafkaThread - Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1':
java.lang.ExceptionInInitializerError: null
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:144)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:96)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:534)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/javax.security.auth.Subject.doAs(Subject.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:534)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:332)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:273)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: com.amazonaws.SdkClientException: Error while loading partitions file from com/amazonaws/partitions/endpoints.json
	at com.amazonaws.partitions.PartitionsLoader.loadPartitionFromStream(PartitionsLoader.java:95)
	at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:84)
	at software.amazon.msk.auth.iam.internals.AuthenticationRequestParams.<clinit>(AuthenticationRequestParams.java:41)
	... 19 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.amazonaws.partitions.model.Partitions`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (ByteArrayInputStream); line: 2, column: 3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
```

**Comment by fhussonnois** [comment]
Hi @chrisoberle, if by any chance you have GraalVM installed (e.g., via SDKMan: `sdk install java 17.0.7-graal`), then you can run your Jikkou command using the `fatjar` with the `native-image-agent` : 

`$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=./ -jar jikkou-runner.jar apply -f jikkou/sandbox/topics.yaml --dry-run`

This command will generate the following files: 
- `reflect-config.json`
- `resource-config.json`

Then I should be able to use that files to complete to fully add support for native build.

In meanwile, I will published another fix for last error.

Thanks.

**Comment by chrisoberle** [comment]
Here you are sir!   
[native-image-agent-configs.zip](https://github.com/streamthoughts/jikkou/files/12559642/native-image-agent-configs.zip)

**Comment by fhussonnois** [comment]
Wow, thank you so much for your help 😃! The early access release is updated :)

**Comment by chrisoberle** [comment]
Its my pleasure sir.  This is quite the utility you've put together.   We're using it every day.

So the latest early access looks like it works!   the command runs fine, however there is an IO exception...but it doesn't *appear* to be causing any obvious issue besides cluttering up stdout:

```
❯ /Users/coberle/Downloads/jikkou-0.28.0-SNAPSHOT-osx-x86_64/bin/jikkou apply -f jikkou/sandbox/topics.yaml --dry-run
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@7a92922
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:127)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:86)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
	at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:968)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:672)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:560)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:644)
	at com.amazonaws.auth.internal.AWS4SignerUtils.formatDateStamp(AWS4SignerUtils.java:39)
	at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:112)
	at com.amazonaws.auth.AWS4Signer.presignRequest(AWS4Signer.java:291)
	at software.amazon.msk.auth.iam.internals.AWS4SignedPayloadGenerator.signedPayload(AWS4SignedPayloadGenerator.java:61)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:142)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:96)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:534)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/javax.security.auth.Subject.doAs(Subject.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:534)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:332)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:273)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
TASK [NONE] Unchanged topic 'dev.canary' (partitions=3, replicas=3, configs=[cleanup.policy=delete,retention.ms=604800000]) - OK
... // other output
EXECUTION in 3s 6ms (DRY_RUN)
ok : 4, created : 0, altered : 0, deleted : 0 failed : 0
```

**Comment by chrisoberle** [comment]
It looks like maybe the early access was updated again bc I'm no longer getting the jodatime-related error when running it.

**Comment by fhussonnois** [comment]
This issue should now be completely fixed in latest release.
