### ISSUE TITLE
Missing joda time in graal binary 

### ISSUE THREAD

**Issue by chrisoberle** [streamthoughts/jikkou#317]
**Describe the bug**
It appears that there are missing joda time classes.  Classloader exceptions are found in the logs when using MSK.   

**To Reproduce**
Using MSK IAM authentication, attempt to apply changes.

**Expected behavior**
Changes should apply without any classloader exception.

**Screenshots/Configs**
```
> jikkou config use-context preprod
> jikkou apply -f topics.yaml
java.io.IOException: Resource not found: "org/joda/time/tz/data/Etc/GMT" ClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@326de728
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneData(ZoneInfoProvider.java:225)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:160)
	at org.joda.time.tz.ZoneInfoProvider.getZone(ZoneInfoProvider.java:164)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:968)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:672)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:560)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:644)
	at com.amazonaws.auth.internal.AWS4SignerUtils.formatDateStamp(AWS4SignerUtils.java:39)
	at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:112)
	at com.amazonaws.auth.AWS4Signer.presignRequest(AWS4Signer.java:291)
	at software.amazon.msk.auth.iam.internals.AWS4SignedPayloadGenerator.signedPayload(AWS4SignedPayloadGenerator.java:61)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:142)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:96)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:534)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/javax.security.auth.Subject.doAs(Subject.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:534)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:332)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:273)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
...
...
...
[EXECUTION in 3s 381ms 
[ok : 348, created : 0, altered : 0, deleted : 0 failed : 0
```

**Runtime environment**
 - OS: Red Hat UBI9
 - Jikkou: 0.30.0 (jikkou binary linux-x86_64)
 - Docker version: [e.g. 18.03.1-ce]
 - Kafka Cluster Version: 2.8.2

**Additional context**
It seems as though this error is just noise in the logs since the changes still appear to apply.   We have noted similar issues in other applications, and explicitly adding the tzdata package helped.   I'm not sure if that is the case here.

**Comment by fhussonnois** [comment]
Hi @chrisoberle, thank you for reporting that issue. I've pushed a fix attempt that should be able through the early-release.

**Comment by chrisoberle** [comment]
This fixed the problem.  Thanks @fhussonnois !
