### ISSUE TITLE
Docker image: can't add SchemaCompatibilityValidation

### ISSUE THREAD

**Issue by minionOfZuul** [streamthoughts/jikkou#361]
**Describe the bug**
I'm very new to jikkou and I'm using the docker image to get familiarized. I wanted to add the SchemaCompatibilityValidation to my configuration, but I'm getting this error:

```
Error: RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.streamthoughts.jikkou.core.models.NamedValue and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized (through reference chain: java.util.HashMap["jikkou.io/managed-by-location"])
```

**To Reproduce**
jikkouconfig
```
{
  "currentContext" : "local",
  "local" : {
    "configFile" : null,
    "configProps" : {
      "kafka.client.bootstrap.servers" : "broker:29092"
    }
  }
}
```
application.conf
```
jikkou {
  validations = [
    {
      name = "topicMustHaveValidName"
      type = io.streamthoughts.jikkou.kafka.validation.TopicNameRegexValidation
      priority = 100
      config = {
        topicNameRegex = "[a-zA-Z0-9\\._\\-]+"
        topicNameRegex = ${?VALIDATION_DEFAULT_TOPIC_NAME_REGEX}
      }
    },
    {
      name = "topicMustHavePartitionsEqualsOrGreaterThanOne"
      type = io.streamthoughts.jikkou.kafka.validation.TopicMinNumPartitionsValidation
      priority = 100
      config = {
        topicMinNumPartitions = 1
        topicMinNumPartitions = ${?VALIDATION_DEFAULT_TOPIC_MIN_NUM_PARTITIONS}
      }
    },
    {
      name = "topicMustHaveReplicasEqualsOrGreaterThanOne"
      type = io.streamthoughts.jikkou.kafka.validation.TopicMinReplicationFactorValidation
      priority = 100
      config = {
        topicMinReplicationFactor = 1
        topicMinReplicationFactor = ${?VALIDATION_DEFAULT_TOPIC_MIN_REPLICATION_FACTOR}
      }
    },
    {
      name = "schemaCompatibility"
      type = io.streamthoughts.jikkou.schema.registry.validation.SchemaCompatibilityValidation
      priority = 100
    }
  ]
}
```

invocation
```
docker run -it --rm --net kafka --mount type=bind,source="$(pwd)"/jikkouconfig,target=/etc/jikkou/config --mount type=bind,source="$(pwd)"/test-schema.avsc,target=/etc/jikkou/tmnt.avsc --mount type=bind,source="$(pwd)"/test.yaml,target=/etc/jikkou/test.yaml --mount type=bind,source="$(pwd)"/application.conf,target=/app/application.conf -e JIKKOU_DEFAULT_SCHEMA_REGISTRY_URL=http://schema-registry:8086 streamthoughts/jikkou:latest update -f /etc/jikkou/test.yaml --dry-run
```

full output
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.streamthoughts.jikkou.core.models.NamedValue and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized (through reference chain: java.util.HashMap["jikkou.io/managed-by-location"])
        at io.streamthoughts.jikkou.client.command.validate.ValidationErrorsWriter.getDetailsAsString(ValidationErrorsWriter.java:85)
        at io.streamthoughts.jikkou.client.command.validate.ValidationErrorsWriter.write(ValidationErrorsWriter.java:52)
        at io.streamthoughts.jikkou.client.command.reconcile.BaseResourceCommand.call(BaseResourceCommand.java:70)
        at io.streamthoughts.jikkou.client.command.reconcile.BaseResourceCommand.call(BaseResourceCommand.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.streamthoughts.jikkou.client.Jikkou.executionStrategy(Jikkou.java:159)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.streamthoughts.jikkou.client.Jikkou.execute(Jikkou.java:149)
        at io.streamthoughts.jikkou.client.Jikkou.main(Jikkou.java:137)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.streamthoughts.jikkou.core.models.NamedValue and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized (through reference chain: java.util.HashMap["jikkou.io/managed-by-location"])
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1330)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:49)
        at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:30)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4793)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4038)
        at io.streamthoughts.jikkou.client.command.validate.ValidationErrorsWriter.getDetailsAsString(ValidationErrorsWriter.java:83)
        ... 15 more

Error: RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.streamthoughts.jikkou.core.models.NamedValue and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized (through reference chain: java.util.HashMap["jikkou.io/managed-by-location"])

```
**Expected behavior**
I was trying to test an incompatible change in the .avsc file, so I expected jikkou to run without failure and tell me that the schema doesn't pass validation

**Runtime environment**
 - docker
 - Jikkou: 0.33.0
 - Docker Desktop 4.25.2
 - Kafka Cluster Version: Confluent Platform 7.5.1

**Comment by fhussonnois** [comment]
Hi @minionOfZuul, thank you for reporting this issue. I will try to reproduce the problem and provide a fix if necessary.  I'll get back to you as soon as possible.

**Comment by fhussonnois** [comment]
hi @minionOfZuul a bugfix release is now available : https://github.com/streamthoughts/jikkou/releases/tag/v0.33.1
It should fix your issue.

**Comment by minionOfZuul** [comment]
Thank you so much. I haven't been able to test it yet, but I should have time today.
