### ISSUE TITLE
Cannot delete Connectors

### ISSUE THREAD

**Issue by jsims-slower** [streamthoughts/jikkou#477]
**Describe the bug**
If you try to delete a Kafka Connect Connector, it throws a NullPointerException.

*This is a showstopper for using Kafka Connect, as you cannot use it for deletes at all.*

**To Reproduce**
Have an existing/deployed Connector, and then add the delete annotation, such as:

```yaml
  metadata:
    name: test-connector
    labels:
      kafka.jikkou.io/connect-cluster: my-connect-cluster
    annotations:
      jikkou.io/delete: true
  ...
```

And if you run `jakku delete` or `jakku apply` you get

```java
java.lang.NullPointerException
	at io.streamthoughts.jikkou.kafka.connect.change.KafkaConnectorChangeComputer$KafkaConnectorChangeFactory.createChangeForUpdate(KafkaConnectorChangeComputer.java:70)
	at io.streamthoughts.jikkou.kafka.connect.change.KafkaConnectorChangeComputer$KafkaConnectorChangeFactory.createChangeForDelete(KafkaConnectorChangeComputer.java:48)
	at io.streamthoughts.jikkou.kafka.connect.change.KafkaConnectorChangeComputer$KafkaConnectorChangeFactory.createChangeForDelete(KafkaConnectorChangeComputer.java:39)
	at io.streamthoughts.jikkou.core.reconciler.change.ResourceChangeFactory.createChange(ResourceChangeFactory.java:33)
	at io.streamthoughts.jikkou.core.reconciler.change.ResourceChangeFactory.createChange(ResourceChangeFactory.java:20)
	at io.streamthoughts.jikkou.core.reconciler.change.DefaultChangeComputer.createChange(DefaultChangeComputer.java:97)
	at java.base@21.0.2/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base@21.0.2/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@21.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@21.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.streamthoughts.jikkou.core.reconciler.change.DefaultChangeComputer.computeChanges(DefaultChangeComputer.java:92)
	at io.streamthoughts.jikkou.core.reconciler.change.DefaultChangeComputer.computeChanges(DefaultChangeComputer.java:67)
	at io.streamthoughts.jikkou.core.reconciler.change.ResourceChangeComputer.computeChanges(ResourceChangeComputer.java:48)
	at io.streamthoughts.jikkou.kafka.connect.reconciler.KafkaConnectorController.plan(KafkaConnectorController.java:121)
	at io.streamthoughts.jikkou.core.DefaultApi.lambda$getDiff$12(DefaultApi.java:552)
	at java.base@21.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@21.0.2/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@21.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@21.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@21.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.streamthoughts.jikkou.core.DefaultApi.getDiff(DefaultApi.java:556)
	at io.streamthoughts.jikkou.core.DefaultApi.reconcile(DefaultApi.java:396)
	at io.streamthoughts.jikkou.client.command.reconcile.BaseResourceCommand.call(BaseResourceCommand.java:54)
	at io.streamthoughts.jikkou.client.command.reconcile.BaseResourceCommand.call(BaseResourceCommand.java:30)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at io.streamthoughts.jikkou.client.Jikkou.executionStrategy(Jikkou.java:150)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.streamthoughts.jikkou.client.Jikkou.execute(Jikkou.java:140)
	at io.streamthoughts.jikkou.client.Jikkou.main(Jikkou.java:128)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)


```

**Expected behavior**
The Connector should be deleted.

**Screenshots/Configs**

**Runtime environment**
 - OS: Ubuntu
 - Jikkou: 0.35.0
 - Docker version: Not Relevant (can reproduce using source)
 - Kafka Cluster Version: 7.5.0

**Additional context**

The problem is that the code that creates the ResourceChange assumes the `after` exists, but for a DELETE it is null.
For a CREATE, `before` is null and `after` is non-null, and that works fine.
Same for an Update, where both `before` and `after` are non-null.
I tested a fix locally that short-circuits to `before` if `after` is null, and it works.

My fix:
```diff
diff --git a/providers/jikkou-provider-kafka-connect/src/main/java/io/streamthoughts/jikkou/kafka/connect/change/KafkaConnectorChangeComputer.java b/providers/jikkou-provider-kafka-connect/src/main/java/io/streamthoughts/jikkou/kafka/connect/change/KafkaConnectorChangeComputer.java
index 4de01901..b579bcf7 100644
--- a/providers/jikkou-provider-kafka-connect/src/main/java/io/streamthoughts/jikkou/kafka/connect/change/KafkaConnectorChangeComputer.java
+++ b/providers/jikkou-provider-kafka-connect/src/main/java/io/streamthoughts/jikkou/kafka/connect/change/KafkaConnectorChangeComputer.java
@@ -67,7 +67,11 @@ public final class KafkaConnectorChangeComputer extends ResourceChangeComputer<S
             );
             return GenericResourceChange
                     .builder(V1KafkaConnector.class)
-                    .withMetadata(after.getMetadata())
+                    .withMetadata(Optional
+                            .ofNullable(after)
+                            .orElse(before)
+                            .getMetadata()
+                    )
                     .withSpec(ResourceChangeSpec
                             .builder()
                             .withOperation(Change.computeOperation(changes))
```

**Comment by jsims-slower** [comment]
Deleting Connectors works in the previous version (0.34.0), so this is likely a regression.

**Comment by fhussonnois** [comment]
Hi @jsims-slower, thank you very much for opening this issue and for the proposed fix. A bugfix version will be released!
