### ISSUE TITLE
NullPointerException when creating default client or user quota

### ISSUE THREAD

**Issue by jeroen92** [streamthoughts/jikkou#489]
First off, thank you for the effort you put into Jikkou, it's a very useful tool!

**Describe the bug**
When creating a `KafkaClientQuota` of type `USERS_DEFAULT`, `CLIENTS_DEFAULT` or `USER_ALL_CLIENTS`, a `NullPointerException` gets thrown:
```java.lang.NullPointerException: value should not be null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
        at io.streamthoughts.jikkou.core.models.NamedValue.<init>(NamedValue.java:32)
        at io.streamthoughts.jikkou.core.models.NamedValueSet.lambda$setOf$1(NamedValueSet.java:57)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at io.streamthoughts.jikkou.core.models.NamedValueSet.setOf(NamedValueSet.java:57)
        at io.streamthoughts.jikkou.core.models.change.ResourceChangeSpecBuilder.withData(ResourceChangeSpecBuilder.java:49)
        at io.streamthoughts.jikkou.kafka.change.quota.KafkaClientQuotaChangeComputer$KafkaClientQuotaChangeFactory.buildChange(KafkaClientQuotaChangeComputer.java:101)
        at io.streamthoughts.jikkou.kafka.change.quota.KafkaClientQuotaChangeComputer$KafkaClientQuotaChangeFactory.createChangeForCreate(KafkaClientQuotaChangeComputer.java:57)
        at io.streamthoughts.jikkou.kafka.change.quota.KafkaClientQuotaChangeComputer$KafkaClientQuotaChangeFactory.createChangeForCreate(KafkaClientQuotaChangeComputer.java:42)
        at io.streamthoughts.jikkou.core.reconciler.change.ResourceChangeFactory.createChange(ResourceChangeFactory.java:22)
        ....
```

The `NamedValue` constructor in `core/src/main/java/io/streamthoughts/jikkou/core/models/NamedValue.java` (https://github.com/streamthoughts/jikkou/blob/main/core/src/main/java/io/streamthoughts/jikkou/core/models/NamedValue.java#L29) requires non-null values. However, `DEFAULT` in `providers/jikkou-provider-kafka/src/main/java/io/streamthoughts/jikkou/kafka/model/KafkaClientQuotaType.java` (https://github.com/streamthoughts/jikkou/blob/main/providers/jikkou-provider-kafka/src/main/java/io/streamthoughts/jikkou/kafka/model/KafkaClientQuotaType.java#L271) is set to `null`, which is used by Kafka Client Quota Types of ` USERS_DEFAULT`, `USER_ALL_CLIENTS` and `CLIENTS_DEFAULT`.

**To Reproduce**
Create a Quota using the following manifest:
```---
apiVersion: 'kafka.jikkou.io/v1beta2'
kind: 'KafkaClientQuota'
spec:
  type: USERS_DEFAULT
  configs:
    requestPercentage: 10
    consumerByteRate: 1024
    producerByteRate: 1024
```
And apply using `JIKKOUCONFIG=../jikkou.conf jikkou apply --dry-run -f ./default_principal_quota.yaml` (I'm using the API proxy).

Alternatively the following unit tests also triggers the bug: https://gist.github.com/jeroen92/6b91dfb9e8c9006492303b5d569b9375

**Expected behavior**
I'd have expected Jikkou to generate a diff, adding the requested client quota.

**Screenshots/Configs**

**Runtime environment**
 - OS: Ubuntu 22
 - Jikkou: 0.34.0
 - Docker version: 26.1.4,
 - Kafka Cluster Version: 3.6.2

**Additional context**
I'm wondering if the fix is as simple as changing `DEFAULT` from `null` to `""`. So I'd rather have some feedback from a maintainer before submitting a PR.

**Comment by fhussonnois** [comment]
Hi @jeroen9, thank you very much for that issue, all your details, and your contribution proposition. Digging into the problem, I fixed it as it was relatively quick to do.

**Comment by jeroen92** [comment]
Thanks @fhussonnois ! Just tested the snapshot release, it works well :)
